name: Greeting from Alessandro Figo Saleh
on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Alessandro
        MIDDLE_NAME: Figo
        LAST_NAME: Saleh
      run:  |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
